name: PULL REQUEST 

on:
  push:
    branches:
      - PULL REQUEST BRANCH

jobs:
  HerokuDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "0333"
          envkey_POSTGRES_DB: "tests"
          envkey_DATABASE_URL: "postgresql://postgres:0333@db:5432/tests"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test
      - name: Build
        run: npm i && npm run build